### ISSUE TITLE
Missing 'create cloud environment' instructions

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#1]
# Module: 2
#### Step: 2

Description of issue

The instructions for M02/Exer2/Step 2 say '**_Click on your project that you created in the cloud environment that has been deployed on your Azure Pass subscription.'_** however in no instructions here, or in the MCT-downloadable TrainersPrepGuide, Handbook, or PowerPoint, can I find any hint of the process used to do that.
 
Can you refer me to where these instructions exist?

Alternatively - If this step, and also the steps using LCS/Cloud enviro in Exercise 3, are no longer intended to be done in this version of the course, it would be good to re-work instructions to excise the references.  If this is still intended to be completed and covered in this course - addt'l instructions would be called for.

**Comment by janeteblake** [comment]
Thank you for reporting this issue. This is done - LCS labs were removed October 3, and the course completely updated October 30. The new labs should work much better!
