### ISSUE TITLE
ER Report links are broken

### ISSUE THREAD

**Issue by LaurieHeer** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#10]
Lab: 01
Exercise: 02
Task: 03

ER Solution links are invalid

https://mbs.microsoft.com/files/public/CS/AX/Customerinvoicingmodelversion2.xml
Customer FTI report(GER).version.2.3.xml

https://mbs.microsoft.com/files/public/CS/AX/CustomerFTIreportGERversion23.xml
Sample ER payment checks solution

Model for cheques.version.10.xml

Cheques printing format.version.10.9.xml

https://mbs.microsoft.com/files/public/CS/AX/Chequesprintingformatversion109.xml
Sample ER foreign trade solution

Intrastat model.version.1.xml

https://mbs.microsoft.com/files/public/CS/AX/Intrastatmodelversion1.xml
Intrastat report.version.1.9.xml

https://mbs.microsoft.com/files/public/CS/AX/Intrastatreportversion19.xml

**Comment by hakimmartin** [comment]
Hi @LaurieHeer - This lab exercise has been updated last month removing those broken links. Can you please try to complete the lab from this page? 

https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/blob/master/Instructions/Labs/MB-300T00A-ENU-PracticeLab_M01E02.md

**Comment by LaurieHeer** [comment]
Thank you for updating the materials and responding quickly. I have contacted GoDeploy support to let them know that there is an update available.

**Comment by SiccoAntuma** [comment]
The links are working, only the XML files are incorrect - during upload the following error message is displayed:

'>' is an unexpected token. The expected token is '='. Line 75, position 90. 

This applies for files Customerinvoicingmodelversion2.xml and CustomerFTIreportGERversion23.xml in trial environment 10.0.15 (10.0.644.10015; PU39)

**Comment by hakimmartin** [comment]
@SiccoAntuma Is there any way that you can retry this lab in a different session, also clearing cache. I have just successfully completed the lab using the xml files provided with no error. 


[Lab01Excercise2XML.zip](https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/files/6460341/Lab01Excercise2XML.zip)
