### ISSUE TITLE
MB-300T00A-ENU-PracticeLab_M01E03.md - image link broken

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#12]
# Module: 01
#### Step: 14

Description of issue:  In Exercise 3/Step 14, the image appears broken.  One way to fix for it:

Step 14 is currently:

14. Select **Show Filter** control as you see in the image below.  
    
    ![](Instructions/media/ShowFiltersButton.PNG)

The link reference could be changed to:

    ![](../media/ShowFiltersButton.PNG)

**Comment by hakimmartin** [comment]
Image link updated.
