### ISSUE TITLE
Mobile App Not Accessible by Android/iPhone When VM Hosted

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#2]
# Module: 05
#### Step: 00

Description of issue
Although the first Task ('Create Mobile Workspaces') is possible to accomplish within the downloadable VM for this course, when this VM is placed in a hosted lab environment - and due to the way the Dynamics site is 'spoofed' to localhost within that VM - it is not accessible by an Android/iPhone on the Internet without substantial modifications and alterations to the VM and/or its networking assumptions.

Will this course be undergoing any updates in the near future to possibly address this issue by (perhaps) a pre-configured Android Emulator being installed to the VM configured to allow access?  (or, alternatively, an Internet-accessible all-online Dynamics test/eval environment that is not dependent on the local VM?)

**Comment by janeteblake** [comment]
Hello there! The course has been updated, so closing this issue. These labs should work much better. We are also updating the VMs on December 15. Please report again if still an issue. Thanks!
