### ISSUE TITLE
No 'GL Detail - Default' report is present.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#3]
# Module: 04
## Lab: 04
Exercise: 01
#### Step: 02

Description of issue
No 'GL Detail - Default' report is present.  Has it been moved or renamed?

**Comment by janeteblake** [comment]
Hello TesterTesterson1004, could you please replace steps 1-6 in that exercise/task with these? Thank you.

Generate a report and explore the data in the report. 
1.	Go to Financial reports under Inquiries and reports in General ledger. 
2.	Select the row for the report named **Ledger Transaction List – Default.**
3.	Click Edit. 
4.	You'll be prompted to download the click-once report designer and to log in. Always allow pop-ups  
5.	Use your credentials to log in. 
6.	Change the parameters as below and select Generate:
- 1.	Base period: 8
- 2.	Base year: **2017**
- 3.	Row: Trial Balance – Default
- 4.	Column: GL Detail - Default
- 5.	Note: If you get no data, try different time periods

**Comment by janeteblake** [comment]
Closed as resolved
