### ISSUE TITLE
Clarify instructions & 'A format code can't be added to a row when a value is present in a link column'' error

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#4]
# Module: 04
## Lab: 04
Exercise: 02
#### Step: 12

Description of issue
The step 12 instruction 'In row 11080, select ---(Underscore amounts)' could be phrased with somewhat more detail to make clear this is to be done in column 'C Format Code'.  

Also, it appears that before this cell is modifiable, one must clear the 'J Link to Financial Dimensions Microsoft Dynamics AX' column otherwise one receives error 'A format code can't be added to a row when a value is present in a link column' when trying to set the Format Code.

**Comment by janeteblake** [comment]
Hello there! The course has been updated, so closing this issue. These labs should work much better.

**Comment by janeteblake** [comment]
Hello there! The course has been updated, so closing this issue. These labs should work much better.
