### ISSUE TITLE
Admin access to AAD

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#40]
# Module: 2
## Lab/Demo: 1

Description of issue
When trying to import  user from AAD, I get an Error 401...user not authorized. The Admin account has lost admin rights to AAD.

Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Can you please provide a screenshot of the error message that shows up at this point? @Tattedgeek
