### ISSUE TITLE
Mod 3, exercise 1, upload templates: Error "Entity <name> does not exist in the target environment"

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#44]
# Module: 03
#### Step: 06

Description of issue

After import templates, a series of warning appear like:
![image](https://user-images.githubusercontent.com/49700217/168862818-10978ffc-4880-41cf-9fe7-04b644a23f77.png)

This error appears directly related to a subsequent inability to see needed/referenced entity, and thus blocks progress on completion of this exercise.

Repro steps:
Take this lab as-written.

-Previously referenced in now-closed issue here:  https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/issues/43  please see a workaround that *might* be suitable to allow the issue to be fixed, would like CO to confirm this is a proper workaround, and if it is - can it be included in the instructions?

If not to be included in the instructions, and there is a specific process that needs to be done in the VM (which is the standard new F&O VM) please detail what this process is.

**Comment by hakimmartin** [comment]
Upon attempting to reproduce this issue we found that you must refresh the entity list. The steps to doing this are:

1.	Navigate to Data Management workspace > Framework parameters 
2.	Select Entity Settings > Refresh entity list. Wait for approximately 15-20 minutes. Close the window.
3.	Click on Templates > Load default templates > Load all.
