### ISSUE TITLE
Module 1, Exercise 2: mbs.microsoft.com site no longer functional - XML files no longer available

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations#7]
# Module: 01
## Exercise 2

Description of issue
mbs.microsoft.com, where these files were hosted, is apparently either down for an extended period of time or has been retired.  From where can Students obtain these files required for Exercise 2?

Once found, can they be added to this repository so they will be always available in the future?

Thanks!

**Missing XML files from https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/blob/master/Instructions/Labs/MB-300T00A-ENU-PracticeLab_M01E02.md:**

 [Sample ER configurations](https://mbs.microsoft.com/customersource/Global/AX/downloads/hot-fixes/365optelecrepeg)

-   **Sample ER customer invoicing solution**

    -   [Customer invoicing
        model.version.2.xml](https://mbs.microsoft.com/files/public/CS/AX/Customerinvoicingmodelversion2.xml)

    -   [Customer FTI report
        (GER).version.2.3.xml](https://mbs.microsoft.com/files/public/CS/AX/CustomerFTIreportGERversion23.xml)

-   **Sample ER payment checks solution**

    -   Model for cheques.version.10.xml

    -   [Cheques printing
        format.version.10.9.xml](https://mbs.microsoft.com/files/public/CS/AX/Chequesprintingformatversion109.xml)

-   **Sample ER foreign trade solution**

    -   [Intrastat
        model.version.1.xml](https://mbs.microsoft.com/files/public/CS/AX/Intrastatmodelversion1.xml)

    -   [Intrastat
        report.version.1.9.xml](https://mbs.microsoft.com/files/public/CS/AX/Intrastatreportversion19.xml)

**Comment by DynamicChipmunk** [comment]
I noticed the same thing, am attaching a .zip file with what I believe to be the correct .xml files for reference.

[MB300XMLfiles.zip](https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/files/6119863/MB300XMLfiles.zip)

**Comment by Guide2Learn** [comment]
Partnersource has been decommissioned. Try https://dynamics.microsoft.com/en-us/support/ 

However all GER files can be downloaded from LCS. 

Soheil Aghazadeh
www.GuideToLearn.com

**Comment by Guide2Learn** [comment]
> I noticed the same thing, am attaching a .zip file with what I believe to be the correct .xml files for reference.
> 
> [MB300XMLfiles.zip](https://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations/files/6119863/MB300XMLfiles.zip)

You are missing one XML for Cheques.

Cheers!

Soheil see my comment below.

**Comment by hakimmartin** [comment]
@DynamicChipmunk Just following up here - I wanted to know how you were accessing the lab and did the files attached above allow you to complete the steps?

**Comment by TesterTesterson1004** [comment]
Not sure about where 'DynamicChipmunk' got the files, but I had sent an email several weeks ago to a support alias that appeared in a Google cache of the retired mbs.microsoft.com site, and they responded with:  

"...As the Customer Source was retired on 15th of Feb 2021, so all the files, documents and hyperlinks got migrated to Microsoft Docs Additional Resources, which is the new landing page for Customer Source.

Go to (https://docs.microsoft.com/en-in/dynamics/s-e/global/additionalresources)
Sign in with your customer source credentials, then go to the Learn Tab, where you should get all the mentioned files..."

I have had no luck finding any of the needed files there, although as I am not a Dynamics expert perhaps someone who is (and has been able to find the files via that method)  might be able to come up with specific step-by-step that can be placed within Instructions here to describe how to find the files?

The only apparent hard copy I have seen is the .zip file attached to this issue.  I had used at least one of the files to step through a portion of the MB-300 lab referencing the files successfully, but have not validated them all 100%.

I am hoping that Course Authors still have an archive, or a back-channel to obtain the 'official' files - or failing that to be able to validate the .zip file is what we need - and then perhaps post them in an 'Allfiles' section of the repository?

**Comment by Guide2Learn** [comment]
Hakim,

I sent you a comprehensive email with two attached files as XML and a new lab.

All ER files are in LCS shared asset library. For convenience i emailed them to you.



Have you got that email?
Soheil.

www.guidetolearn.com<http://www.guidetolearn.com>
________________________________

**Comment by hakimmartin** [comment]
This lab exercise has been updated.
